name: Rust CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Set up specific Rust version
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl

    - name: Cache Cargo registry and build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build Release
      run: cargo build --release --target x86_64-unknown-linux-musl --verbose

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Install NumPy for gcloud performance
      run: sudo apt-get update && sudo apt-get install -y python3-numpy

    - name: Prepare Server via IAP
      run: |
        gcloud compute ssh ${{ secrets.SSH_USER }}@${{ secrets.GCP_VM_NAME }} \
          --project=${{ secrets.GCP_PROJECT }} \
          --zone=${{ secrets.GCP_ZONE }} \
          --tunnel-through-iap \
          --strict-host-key-checking=no \
          --command="cd ~/Web-server-Report-websocket && git pull origin main && git reset --hard origin/main; pkill -f '[w]eb-server-report-websocket' || true; mkdir -p ~/Web-server-Report-websocket/target/release"

    - name: Deploy to Google VM via IAP
      run: |
        gcloud compute scp target/x86_64-unknown-linux-musl/release/web-server-report-websocket \
          ${{ secrets.SSH_USER }}@${{ secrets.GCP_VM_NAME }}:~/Web-server-Report-websocket/target/release/ \
          --project=${{ secrets.GCP_PROJECT }} \
          --zone=${{ secrets.GCP_ZONE }} \
          --tunnel-through-iap \
          --strict-host-key-checking=no

    - name: Run Application via IAP
      run: |
        gcloud compute ssh ${{ secrets.SSH_USER }}@${{ secrets.GCP_VM_NAME }} \
          --project=${{ secrets.GCP_PROJECT }} \
          --zone=${{ secrets.GCP_ZONE }} \
          --tunnel-through-iap \
          --strict-host-key-checking=no \
          --command="chmod +x ~/Web-server-Report-websocket/target/release/web-server-report-websocket && cd ~/Web-server-Report-websocket && setsid nohup ./target/release/web-server-report-websocket > app.log 2>&1 < /dev/null & exit"
        echo "Application started."
